export enum ErrorCodes {
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  NOT_FOUND = 'NOT_FOUND',
  UNAUTHORIZED = 'UNAUTHORIZED',
  BUSINESS_RULE_VIOLATION = 'BUSINESS_RULE_VIOLATION',
  STATE_TRANSITION_ERROR = 'STATE_TRANSITION_ERROR'
}
