export enum ProjectStatus {
  DRAFT = 'DRAFT',
  PROPOSED = 'PROPOSED',
  REVIEW = 'REVIEW',
  APPROVED = 'APPROVED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  TERMINATED = 'TERMINATED'
}

export enum ProposalStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  REVISION_REQUIRED = 'REVISION_REQUIRED',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED'
}

export enum MemberRole {
  PRINCIPAL_INVESTIGATOR = 'PRINCIPAL_INVESTIGATOR',
  CO_RESEARCHER = 'CO_RESEARCHER',
  RESEARCH_ASSISTANT = 'RESEARCH_ASSISTANT',
  EXTERNAL_COLLABORATOR = 'EXTERNAL_COLLABORATOR'
}

export enum MilestoneStatus {
  PENDING = 'PENDING',
  IN_PROGRESS = 'IN_PROGRESS',
  ACHIEVED = 'ACHIEVED',
  DELAYED = 'DELAYED'
}

export enum FundingType {
  SELF_FUNDED = 'SELF_FUNDED',
  INTERNAL = 'INTERNAL',
  EXTERNAL = 'EXTERNAL',
  GRANT = 'GRANT',
  INDUSTRY = 'INDUSTRY'
}

export enum OutputType {
  JOURNAL = 'JOURNAL',
  CONFERENCE = 'CONFERENCE',
  BOOK = 'BOOK',
  PATENT = 'PATENT',
  PROTOTYPE = 'PROTOTYPE',
  SOFTWARE = 'SOFTWARE',
  DATASET = 'DATASET',
  COMMUNITY_SERVICE = 'COMMUNITY_SERVICE',
  OTHER = 'OTHER'
}
