export enum SubmissionStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  SCREENING = 'SCREENING',
  UNDER_REVIEW = 'UNDER_REVIEW',
  MINOR_REVISION = 'MINOR_REVISION',
  MAJOR_REVISION = 'MAJOR_REVISION',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
  PRODUCTION = 'PRODUCTION',
  PUBLISHED = 'PUBLISHED',
  WITHDRAWN = 'WITHDRAWN'
}

export enum ReviewDecision {
  ACCEPT = 'ACCEPT',
  MINOR_REVISION = 'MINOR_REVISION',
  MAJOR_REVISION = 'MAJOR_REVISION',
  REJECT = 'REJECT'
}

export enum ReviewRoundStatus {
  PENDING = 'PENDING',
  ACCEPTED_INVITATION = 'ACCEPTED_INVITATION',
  DECLINED_INVITATION = 'DECLINED_INVITATION',
  COMPLETED = 'COMPLETED',
  OVERDUE = 'OVERDUE'
}
